### ISSUE TITLE
Add validation to prevent messages to be published in wrong topics

### ISSUE THREAD

**Issue by matheusmosca** [matheusmosca/walrus#12]
Our [Dispatch method](https://github.com/matheusmosca/walrus/blob/main/domain/entities/topic.go#L37) is dispatching any message incoming from the function's parameter. So we need to validate if this message really belongs to this topic. You can create a new error for this validation in [errors.go](https://github.com/matheusmosca/walrus/blob/main/domain/entities/errors.go)

It is also important to add unit tests for this scenario.

**Comment by sptGabriel** [comment]
hey, can I take this issue ?

**Comment by matheusmosca** [comment]
One issue at a time my friend @sptGabriel. you are already assigned to #8, aren't you?

**Comment by sptGabriel** [comment]
hey, I can take it now?
