### ISSUE TITLE
Add unit tests for get_topic.go

### ISSUE THREAD

**Issue by matheusmosca** [matheusmosca/walrus#13]
The file is in here [get_topic.go](https://github.com/matheusmosca/walrus/blob/main/repositories/memory/topics/get_topic.go#L10). Have a look at [create_topic_test.go](https://github.com/matheusmosca/walrus/blob/main/repositories/memory/topics/create_topic_test.go#L13) as an example

**Comment by amoghrajesh** [comment]
@matheusmosca I would like to work on this issue if it is still not assigned to anyone else. Please assign it to me.

**Comment by matheusmosca** [comment]
> @matheusmosca I would like to work on this issue if it is still not assigned to anyone else. Please assign it to me.

Sure, I'll assign it to you @amoghrajesh.

**Comment by amoghrajesh** [comment]
@matheusmosca the usage of the application is not clear yet. We are able to build it but can not figure out how the usage goes.
