### ISSUE TITLE
Use a `sync.Mutex` to avoid concurrency issues

### ISSUE THREAD

**Issue by matheusmosca** [matheusmosca/walrus#14]
We know that 2 or more applications can start a subscription connection to a topic at the same time, but if this topic does not exist already, then there is a chance to it be created twice. It turns out that some subscribers won't get subscribed correctly, since the topic will get overwritten with only the last subscription.

To solve it, we can use a mutex which can be locked when a new topic is starting to be created. With this approach, only one topic can be created at a time, it does not seem a problem to me since the topic creation process is pretty fast.

So you can add a `*sync.Mutex` field in [repository struct](https://github.com/matheusmosca/walrus/blob/main/repositories/memory/topics/repository.go#L10) and use it in [create_topic.go](https://github.com/matheusmosca/walrus/blob/main/repositories/memory/topics/create_topic.go#L10)

**Comment by Olsi-B** [comment]
PR #18
