### ISSUE TITLE
Add unit tests for rpc/v1/publish.go

### ISSUE THREAD

**Issue by matheusmosca** [matheusmosca/walrus#31]
You can find the file [here](https://github.com/matheusmosca/walrus/blob/main/rpc/v1/publish.go). Take a look at [this StackOverflow post](https://stackoverflow.com/questions/42102496/testing-a-grpc-service) for more info about gRPC testing in Go.

**Comment by matheusmosca** [comment]
I'll assign you on this one @Smelton01

**Comment by Smelton01** [comment]
@matheusmosca looking forward to contributing
