### ISSUE TITLE
Add unit tests for publish use case

### ISSUE THREAD

**Issue by matheusmosca** [matheusmosca/walrus#8]
The file is in here: [publish.go](https://github.com/matheusmosca/walrus/blob/main/domain/usecases/publish.go#L9)

Steps: 

1. Create a file `publish_test.go` in the same directory
2. Create a mock for the [repository interface](https://github.com/matheusmosca/walrus/blob/main/domain/usecases/usecase.go#L17). I recommend using [matryer/moq](https://github.com/matryer/moq) for it, but suggestions are welcome
3. Start testing! :vertical_traffic_light:

**Comment by sptGabriel** [comment]
hey, can I take this issue ?

**Comment by matheusmosca** [comment]
Sure @sptGabriel

**Comment by sptGabriel** [comment]
hey, @matheusmosca can check this pr: https://github.com/matheusmosca/walrus/pull/22?
