### ISSUE TITLE
Add unit tests for subscribe use case

### ISSUE THREAD

**Issue by matheusmosca** [matheusmosca/walrus#9]
The file is in here: [subscribe.go](https://github.com/matheusmosca/walrus/blob/main/domain/usecases/subscribe.go#L11)

Steps: 

1. Create a file `subscribe_test.go` in the same directory
2. Create a mock for the [repository interface](https://github.com/matheusmosca/walrus/blob/main/domain/usecases/usecase.go#L17). I recommend using [matryer/moq](https://github.com/matryer/moq) for it, but suggestions are welcome
3. Start testing! :vertical_traffic_light:

**Comment by sptGabriel** [comment]
hey, can I take this issue ?

**Comment by quanuw** [comment]
Hi @matheusmosca, can I work on this issue?

**Comment by matheusmosca** [comment]
> Hi @matheusmosca, can I work on this issue?

Sure, @quanuw ! Go ahead

**Comment by matheusmosca** [comment]
Hi @quanuw, are you still working on this issue? I've noticed you didn't fork the repository yet.

**Comment by quanuw** [comment]
@matheusmosca Yes, I'm starting on it today.
